### ISSUE TITLE
mask radius wizard values make no sense

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em#106]
![image](https://user-images.githubusercontent.com/6952870/86396041-254c5880-bc99-11ea-9540-5aa9a0534dad.png)

**Comment by pconesa** [comment]
@JorMaister has this been fixed?

**Comment by JorMaister** [comment]
Not yet. Is it a scale problem? Can you provide me a little more information for how would those values be correct?

**Comment by azazellochg** [comment]
Endless wizard problems continue: https://github.com/scipion-em/scipion-em/blob/devel/pwem/wizards/wizard.py#L867 this unit is not used at all in the function. 
My code:
```
class GautomatchParticleWizard(emwiz.ParticleMaskRadiusWizard):
    _targets = [(ProtGautomatch, ['particleSize'])]
    
    def _getParameters(self, protocol):
        
        label, value = self._getInputProtocol(self._targets, protocol)
        
        protParams = dict()
        protParams['input'] = protocol.inputReferences
        protParams['label'] = label
        protParams['value'] = value
        return protParams
    
    def _getProvider(self, protocol):
        _objs = self._getParameters(protocol)['input'] 
        return emwiz.ParticleMaskRadiusWizard._getListProvider(self, _objs)
    
    def show(self, form, *args):
        params = self._getParameters(form.protocol)
        _value = params['value']
        _label = params['label']
        emwiz.ParticleMaskRadiusWizard.show(self, form, _value, _label,
                                            UNIT_ANGSTROM)
```

The wizard sets/gets value in pixels, while I tell it I want angstroms.

**Comment by JorMaister** [comment]
Hi @azazellochg, 
I'd beg you to only describe the error found. Personally I think that judgement values such adjetive endless aren't possitive at allí.

**Comment by azazellochg** [comment]
Hi @JorMaister , I'm afraid there is not much positive about these errors. There is more: CtfDownsampleDialog doesn't consider downsampling for the allowed freq. range (below max freq should be 5A not 2.5A)
![image](https://user-images.githubusercontent.com/6952870/90340113-aa8f9080-dfed-11ea-9d72-c995a90288da.png)

**Comment by JorMaister** [comment]
Hi @azazellochg,
What I mean is despite the fact that there can be errors present in the code, that kind comments such as 'endless' may be interpreted as beligerant attitude for other project collaborators, which may not be possitive for a collaborative project as Scipion.
Anycase, thanks for reporting. We'll work on it.
