### ISSUE TITLE
chimera show angular distribution does not longer work

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-em#107]
**Describe the bug**
I already commented on this bug in slack but I just report it here:  the viewer of "relion 3D classification" does not work any longer for the option "Display angular distribution - chimera"

**To Reproduce**

   Execute protocol relion 3D classification
   open Analize
   select Display angular distribution - chimera
   chimera opens briefly and closes

**Expected behavior**
Show angular distribution plot

**Desktop (please complete the following information):**
 - Scipion version: 3
 - Relion plugin version [e.g. 1.0.6]  devel

**Additional context**
I think the problem is the recent simplication of the chimera viewer.

Before we have the code 

````class ChimeraClientView(CommandView):
    """ View for calling an external command. """
    def __init__(self, inputFile, **kwargs):
        self._inputFile = inputFile
        self._kwargs = kwargs
    def show(self):
        if self._kwargs.get('showProjection', False):
            ChimeraProjectionClient(self._inputFile, **self._kwargs)
        else:
            ChimeraAngDistClient(self._inputFile, **self._kwargs
```

but it has been removed and ChimeraAngDistClient is never called. I think @pconesa  was involved in the simplification.

**Comment by azazellochg** [comment]
I removed ":mrc" from filenames, so the volumes open but no ang dist displayed. This is broken in eman2 and spider as well. Transferred to pwem

**Comment by pconesa** [comment]
This should be working now.
I'm closing this issue. Feel free to reopen it if I'm wrong or missed something.
