### ISSUE TITLE
Probably wrong version check

### ISSUE THREAD

**Issue by DStrelak** [scipion-em/scipion-em#117]
When I run scipion3, I get `The package scipion-pyworkflow is out of date. Your version is 3.0.0a11, the latest is 3.0.0.`
It seems that the check does not expect `a11`.

Branch 'devel'

**Comment by pconesa** [comment]
It does, semantic versioning site says:
"Pre-release versions have a lower precedence than the associated normal version"

So, 3.0.0a11 is lower than 3.0.0
