### ISSUE TITLE
Sampling rate is lost on averages set.

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em#136]
https://github.com/scipion-em/scipion-em/commit/ce21d24e803fb39ec4c545035f289d2724a5bde3

**Comment by azazellochg** [comment]
output.copyInfo(inputImages) already supposed to copy sampling rate, why do we need that commit?

**Comment by pconesa** [comment]
That commit is to allow "representatives" (averages) to have a different sampling rate than the images. This was triggered by the fact that CS 2d classification and ab initio, in some cases output downscaled images and the plugin, by mistake was registered them at the same sampling rate as the images.

We are changing this and we want to scale the volumes/averages back to match the images. But also we looked at the option of having different dimensions in the representative and this commit allows it...although accidentally is breaking the sampling rate, which should be easy to fix.
