### ISSUE TITLE
Cannot open maps with ChimeraX after creating a set of maps

### ISSUE THREAD

**Issue by mmmtnez** [scipion-em/scipion-em#178]
Hi all,

when you execute the protocol pwem/protocols/protocol_sets.py you cannot visualize the maps with ChimeraX. After pressing Anbalyze Results a results' window is opened. When you select File -> Open with ChimeraX the ChimeraX GUI tries to open but finally gets closed. I've observed this in the test:

scipion3 tests pwem.tests.protocols.test_protocols_import_volumes.TestImportVolumes

(there is only one case of creation of set of maps)

**Comment by azazellochg** [comment]
Duplicate of the https://github.com/scipion-em/scipion-pyworkflow/issues/157
