### ISSUE TITLE
join sets ignore duplicates issue

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em#186]
This param looks inverted. If I say Yes, it does not ignore and vice versa.

**Comment by pconesa** [comment]
What do you expect it to do? If active Yes it should "skip" the item with an id already added.

**Comment by azazellochg** [comment]
I guess I didnt read the long help for this item. For me ignoring duplicates meant "ignore that I join duplicate items" and add them anyway.

**Comment by azazellochg** [comment]
you can close this if u want

**Comment by pconesa** [comment]
yes, I think we could find a better label. Because both meanings fit. 

"Skip duplicates" ?

**Comment by pconesa** [comment]
"Skip duplicated ids"?

**Comment by azazellochg** [comment]
Maybe "Remove duplicates?" with default value "Yes" which will prevent people accidentally joining same items and having problems later.

**Comment by pconesa** [comment]
I don't think is a good idea to "invert" the meaning without creating confusion to the developers or breaking compatibility. Although your suggestion is much clearer.

What about: "Renumber duplicates?" or "Renumber duplicated ids?"  or "Keep duplicated is?"

Default value can  be changed to True.

**Comment by pconesa** [comment]
You see! this is confusing, my suggestions are inverting the meaning.

My suggestions are not valid, should retain that same meaning with "False" or "True"

**Comment by pconesa** [comment]
Skip duplicated ids
Remove duplicated ids
Bin duplicated ids

I think similar to this ones will not invert the meaning and the behaviour.

**Comment by pconesa** [comment]
So, yours, should work! Remove duplicates... ahhh!!

**Comment by azazellochg** [comment]
if you dont want to change the old value, sure, we can put No for "Remove duplicates". I think including "id" into the label is causing confusion, since taking care of ids can mean a differerent thing compared to taking care of duplicates.

**Comment by pconesa** [comment]
This was addressed.
