### ISSUE TITLE
Import atomic structure in batch?

### ISSUE THREAD

**Issue by yongshuo-Z** [scipion-em/scipion-em#188]
Hi, I have about 100 atomic structures to import and conduct the following processing. Is there any way to import them in batch instead of one by one?

**Comment by pconesa** [comment]
Do you program in python? There is a way, but it require a bit of scripting.

**Comment by yongshuo-Z** [comment]
> Do you program in python? There is a way, but it require a bit of scripting.

Yes. I am now using the GUI. It will be great if there is a way to program directly.

**Comment by pconesa** [comment]
Is it a one time thing? It could be an option to use a workflow template. Just thinking out loud.

**Comment by yongshuo-Z** [comment]
Thanks for the advice. I'm new to this area, but it seems the workflow template can only import movies?  Here is my project flow:
![image](https://user-images.githubusercontent.com/59311975/106102359-3cddb800-617a-11eb-8412-af31e2e4d909.png)

I want to do this in batch. Any advice, please?

**Comment by pconesa** [comment]
Hi, this should more or less do what you want:
````
import os
import sys

import pyworkflow.utils as pwutils
from pyworkflow.project import Manager, Project
from pyworkflow.project import scripts
from pwem.protocols import ProtImportPdb
from xmipp3.protocols import XmippProtConvertPdb, XmippProtCreateGallery


def atomStruct2Gallery(atomStructId: str, project: Project):

    # importAs = project.newProtocol(ProtImportPdb)
    # importAs.pdbId.set(atomStructId)
    # importAs._store()
    # 
    convertPdb = project.newProtocol(XmippProtConvertPdb)
    convertPdb.pdbId.set(atomStructId)
    convertPdb._store()

    xmippGallery = project.newProtocol(XmippProtCreateGallery)
    xmippGallery.inputVolume.set(convertPdb)
    xmippGallery.inputVolume.setExtended("outputVolume")
    xmippGallery._store()



manager = Manager()

if len(sys.argv) == 1:
    print("Need to pass a path to a file with the atomic structures")
    sys.exit(1)

asListFile = sys.argv[1]
projName = "batchAS2gallery"

# Create a new project
if manager.hasProject(projName):
    print("There is already a project with this name: %s"
          % pwutils.red(projName))
    sys.exit(2)

if asListFile is not None and not os.path.exists(asListFile):
    print("Nonexistent file: %s" % pwutils.red(asListFile))
    sys.exit(3)


project = manager.createProject(projName)

with open(asListFile) as fh:
    for pdbId in fh:
        atomStruct2Gallery(pdbId[:-1], project)

print("To launch the project run: ")
print("scipion3 python %s/schedule.py %s" % (scripts.__path__._path[0], projName))

````

You must have a txt file with pdbIds, in my case --> pdbs.txt

````
4HHB
4HHB
````

To use it:

1.- Have your txt with pdbIds written, I'll assume is pdbs.txt
2.- Create the project: `scipion3 python batchpdb2gallery.py pdbs.txt `
3.-At the end you will see a line to launch it similar to this one:
`scipion3 python /home/pablo/desarrollo/scipion-pyworkflow/pyworkflow/project/scripts/schedule.py batchAS2gallery`

4.- If you are happy with the project created, schedule the project using the printed command.

NOTE: It can be adapted to use local files instead of downloading files: find some hints here -->https://github.com/I2PC/scipion-em-xmipp/blob/ca5bce5aaf8a1149c252c72ef9a61fcc59aa0953/xmipp3/protocols/protocol_convert_pdb.py#L48


Another, maybe straight approach would be to use xmipp commands instead of scipion, providing atomicstructure files are local.


Let me know if you need anything else.

**Comment by yongshuo-Z** [comment]
Thank you very very much for the code!! But I think I need to bother you again:)

Following your instructions, I have created the project and put two pdb IDs in the .txt file. After running the batchAS2gallery, the command line shows:
```
Scipion v3.0.7 - Eugenius
** Running command: 'python3 /opt/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_schedule_run.py "/root/ScipionUserData/projects/batchAS2gallery" "Runs/000002_XmippProtConvertPdb/logs/run.db" 2'
** Running command: 'python3 /opt/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_schedule_run.py "/root/ScipionUserData/projects/batchAS2gallery" "Runs/000039_XmippProtCreateGallery/logs/run.db" 39'
** Running command: 'python3 /opt/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_schedule_run.py "/root/ScipionUserData/projects/batchAS2gallery" "Runs/000077_XmippProtConvertPdb/logs/run.db" 77'
** Running command: 'python3 /opt/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_schedule_run.py "/root/ScipionUserData/projects/batchAS2gallery" "Runs/000114_XmippProtCreateGallery/logs/run.db" 114'
```

and then the cmd appears to run these four lines one by one. However, after finished the first line, it stuck at the second command 
```
** Running command: 'python3 /opt/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_run.py "/root/ScipionUserData/projects/batchAS2gallery" "Runs/000039_XmippProtCreateGallery/logs/run.db" 39'
```

I left it running for about half an hour and it was still running then. So I think maybe there is something wrong?

I checked the project folder. I found that the gallery of the first pdb structure has been successfully exported, but the second one hasn't.

**Comment by pconesa** [comment]
What happens if you do it manually in the GUI? Do you see any error in the logs?

**Comment by yongshuo-Z** [comment]
It works fine with GUI without error in the log.

I have tested some other IDs in the txt file. I found that it always stuck at the above command ending with '39'. The galleries (.stk files) can be created except the last one in the txt file (e.g. if I put 50 ids in the txt file, galleries of the first 49 structures can be created).

Anyway, it won't be a big problem for me and thanks again.

**Comment by yongshuo-Z** [comment]
Hi, sorry to bother you again. When I run the scripts above, it seem the program consumes all of the memory and makes the computer so slow. I wonder is there a way to limit the use of memory (e.g. the maximum use of memory is 50% of the total memory)?

**Comment by pconesa** [comment]
How big is your project?

**Comment by yongshuo-Z** [comment]
I'm just running the above script (almost change nothing) to import pdb structures (400 in total) and convert them to galleries. My computer has 256 GB memory but all of them just run out. quite weird

**Comment by pconesa** [comment]
Maybe add a time.sleep(60)

To wait one minute after each launch will space processing.

60 are seconds, increase it not enough.

**Comment by yongshuo-Z** [comment]
It helps. Thanks!!
