### ISSUE TITLE
boog when calling createSetOfClasses2D()

### ISSUE THREAD

**Issue by jbusselez** [scipion-em/scipion-em#240]
Hola 

When trying to get a subset of 2D classes after a 2d classification (scipion-em version 3.0.11) I got a failure: 

Here is the log extract :

00014:   STARTED: createSetStep, step 1, time 2021-08-02 15:46:29.108992
00015:   Source: xmipp3 - cl2d
00016:   Output type: SetOfClasses2D
00017:   Subset (sqlite) file: Runs/000235_XmippProtCL2D/classes2D_state.sqlite,
00018:   Other: 213
00019:   Traceback (most recent call last):
00020:     File "/home/common/anaconda3-scipion/envs/scipion3/lib/python3.8/site-packages/pwem/protocols/protocol_batch.py", line 382, in _createClassesFromClasses
00021:       output = createFunc()
00022:   TypeError: _createSetOfClasses2D() missing 1 required positional argument: 'imgSet'
00023:   
00024:   During handling of the above exception, another exception occurred:
00025:   
00026:   Traceback (most recent call last):
00027:     File "/home/common/anaconda3-scipion/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 197, in run
00028:       self._run()
00029:     File "/home/common/anaconda3-scipion/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 248, in _run
00030:       resultFiles = self._runFunc()
00031:     File "/home/common/anaconda3-scipion/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 244, in _runFunc
00032:       return self._func(*self._args)
00033:     File "/home/common/anaconda3-scipion/envs/scipion3/lib/python3.8/site-packages/pwem/protocols/protocol_batch.py", line 133, in createSetStep
00034:       self._createSubSetFromClasses(markedSet)
00035:     File "/home/common/anaconda3-scipion/envs/scipion3/lib/python3.8/site-packages/pwem/protocols/protocol_batch.py", line 245, in _createSubSetFromClasses
00036:       return self._createClassesFromClasses(inputClasses)
00037:     File "/home/common/anaconda3-scipion/envs/scipion3/lib/python3.8/site-packages/pwem/protocols/protocol_batch.py", line 384, in _createClassesFromClasses
00038:       output = inputClasses.getClass().createCopy(self._getPath())
00039:   TypeError: createCopy() missing 1 required positional argument: 'outputPath'
00040:   Protocol failed: createCopy() missing 1 required positional argument: 'outputPath'
00041:   FAILED: createSetStep, step 1, time 2021-08-02 15:46:29.197871
00042:   *** Last status is failed

Best 

Johan

**Comment by pconesa** [comment]
Thanks @azazellochg for assigning it.

Johan, could you please send the output of:

`scipion3 run pip list`

**Comment by pconesa** [comment]
@fonsecareyna82 has already fix this. It is a bug on our side.
We are going to release a hotfix

**Comment by pconesa** [comment]
Fix is released: scipion-em 3.0.12

**Comment by pconesa** [comment]
Thanks for reporting it!

**Comment by jbusselez** [comment]
Thanks for the fast fix
