### ISSUE TITLE
protocol_batch

### ISSUE THREAD

**Issue by cossorzano** [scipion-em/scipion-em#318]
The prints of protocol_batch.py line 77 and subsequent cause a UnicodeEncodeError: 'latin-1' codec can't encode character u'xxx' in position 19: ordinal not in range(256)

A simple solution is not to print

**Comment by pconesa** [comment]
Thanks, @cossorzano , do you know how did you ended up with a "non ascii" character in "sourseSet" .... I guess sqlite basename will be ok... is it maybe a non ascii character in your project path?

**Comment by cossorzano** [comment]
It failed again in the machine of the course at Pasteur. Have you fixed it?

**Comment by pconesa** [comment]
I'll remove the print although is not the ideal solution.

**Comment by cossorzano** [comment]
I am sure that you may keep the print if you put some "encode"-something, but I don't know what

**Comment by pconesa** [comment]
Can I access that project?

**Comment by pconesa** [comment]
In this case, in case someone else has this issue. setting the locale of the system to a utf-8 version fixed it:

In ubuntu:
`sudo update-locale LANG=en_GB.utf8`

We will see if there is a better workaround to allow non utf-8 locales, like only using ASCII chars? ;-(
