### ISSUE TITLE
quotes are not working

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em#32]
In https://github.com/scipion-em/scipion-em/blob/devel-fixes/pwem/protocols/protocol_import/volumes.py#L307:

`FileNotFoundError: [Errno 2] No such file or directory: '"/home/azazello/soft/scipion3/scipion_home/data/tests/model_building_tutorial/PDBx_mmCIF/1ake_start.pdb"'`

**Comment by pconesa** [comment]
Were you introducing quotes in the filed?

**Comment by pconesa** [comment]
or is this from a test?

**Comment by azazellochg** [comment]
i cant possibly remember an issue reported half a year ago

**Comment by pconesa** [comment]
True! I've tested a normal import. Test are passing....
I'm closing this issue. Feel free to reopen it if I'm wrong or missed something.
