### ISSUE TITLE
Bio.Alphabet is now removed from new biopython

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em#335]
https://biopython.org/wiki/Alphabet
https://github.com/scipion-em/scipion-em/blob/devel/pwem/objects/data.py#L803

**Comment by rmarabini** [comment]
OK, I will review this with calm. If we remove Alphabet we need to  update biopython.

**Comment by akesandgren** [comment]
Please note that this change in Biopython was done in v1.78 back in 2020.
And no, you do not need to update biopython to get rid of the use of Alphabet, it's the other way around.

**Comment by rmarabini** [comment]
Hi @pconesa , 
     I understand scipion uses right now biopython version 1.76 that requires alphabets. 
Obviously the day that we update biopython to a newer version we need to delete alphabets from the sequence object and import protocols. So the question is, does somebody need a newer version of biopython for any reason?

**Comment by pconesa** [comment]
I think there is no urgency but otherwise, a way to prevent being stuck in an old set of versions.

I'd probably set the aim of updating versions to be compatible with python 3.11 once it is stable enough. (not soon though)
