### ISSUE TITLE
Bug when creating subsets from Showj

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-em#368]
I think I have found a serious bug in showj, when creating outputs from Classification (maybe also in other cases).

For example, 3d classification of particles into 4 classes (volumes here). If I create a subset from particles in class 1 and from the same showj window create subset for class 2. I think showj is only writing a single selection file (state or something) and the first selection can get the actual values from selection 2....and in many classes selection 2 subset protocol fails because some missing file, which I believe that have been deleted by selection 1.

**Comment by pconesa** [comment]
Thanks Jose!
I guess it is a "race condition problem" that might have been there since the begining.

**Comment by pconesa** [comment]
I don't think we will fix this.
