### ISSUE TITLE
Error in installing deepLearningToolkit

### ISSUE THREAD

**Issue by stefanocapaldi** [scipion-em/scipion-em#402]
Hi! I'm trying to install the deepLearningToolkit in Scipion3 to use Xmipp3 deep hand tool, but I got errors when using the plugin manager and from the command line with: scipion installb deepLearningToolkit
the stderr output is:

00001:   ERROR: Ignored the following versions that require a different python version: 1.22.0 Requires-Python >=3.8; 1.22.1 Requires-Python >=3.8; 1.22.2 Requires-Python >=3.8; 1.22.3 Requires-Python >=3.8; 1.22.4 Requires-Python >=3.8; 1.23.0 Requires-Python >=3.8; 1.23.0rc1 Requires-Python >=3.8; 1.23.0rc2 Requires-Python >=3.8; 1.23.0rc3 Requires-Python >=3.8; 1.23.1 Requires-Python >=3.8; 1.23.2 Requires-Python >=3.8; 1.23.3 Requires-Python >=3.8; 1.23.4 Requires-Python >=3.8; 1.23.5 Requires-Python >=3.8; 1.24.0 Requires-Python >=3.8; 1.24.0rc1 Requires-Python >=3.8; 1.24.0rc2 Requires-Python >=3.8; 1.24.1 Requires-Python >=3.8; 1.24.2 Requires-Python >=3.8
00002:   ERROR: Could not find a version that satisfies the requirement numpy==1.23.0 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6)
00003:   ERROR: No matching distribution found for numpy==1.23.0

**Comment by stefanocapaldi** [comment]
in addition to the stderr log of the plugin manager, when trying to install from the command line I've got the following:
Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate xmipp_DLTK_v0.3
#
# To deactivate an active environment, use
#
#     $ conda deactivate

ERROR: Ignored the following versions that require a different python version: 1.22.0 Requires-Python >=3.8; 1.22.1 Requires-Python >=3.8; 1.22.2 Requires-Python >=3.8; 1.22.3 Requires-Python >=3.8; 1.22.4 Requires-Python >=3.8; 1.23.0 Requires-Python >=3.8; 1.23.0rc1 Requires-Python >=3.8; 1.23.0rc2 Requires-Python >=3.8; 1.23.0rc3 Requires-Python >=3.8; 1.23.1 Requires-Python >=3.8; 1.23.2 Requires-Python >=3.8; 1.23.3 Requires-Python >=3.8; 1.23.4 Requires-Python >=3.8; 1.23.5 Requires-Python >=3.8; 1.24.0 Requires-Python >=3.8; 1.24.0rc1 Requires-Python >=3.8; 1.24.0rc2 Requires-Python >=3.8; 1.24.1 Requires-Python >=3.8; 1.24.2 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement numpy==1.23.0 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6)
ERROR: No matching distribution found for numpy==1.23.0
target '/home/stefano/programs/scipion/software/em/deepLearningToolkit/xmipp_DLTK_v0.3.yml' not built (after running 'export PYTHONPATH="" && eval "$(/home/stefano/programs/miniconda/bin/conda shell.bash hook)" && conda create --force --yes -n xmipp_DLTK_v0.3 python=3 pandas=0.23 scikit-image=0.14 opencv=3.4 tensorflow-gpu=1.15 keras=2.2 scikit-learn=0.22  -c anaconda && conda activate xmipp_DLTK_v0.3 && pip install numpy==1.23.0 numpy==1.23.0 && conda env export > xmipp_DLTK_v0.3.yml')

**Comment by albertmena** [comment]
Hello [stefanocapaldi](https://github.com/stefanocapaldi),
When installing DLTK be care about the enviroment you have activated, this is the one the instaler take into acount to install everything. We are working improving (and fixing issues) related to the DLTK, but so far please activate the Scipion enviroment (or anyone with a python >=3.8).
Please dont hesitate contact us again. 
Thanks

**Comment by stefanocapaldi** [comment]
Hi! Sorry but I have no idea of what enviroment is activated.. I follewed the instructions on the webpages for the installation of Scipion3, and all the other plugins work fine.. I just tried to first activate the Scipion3 env "conda activate scipion3" which have the python 3.8.16 (from "python -V") and run the command "scipion3 installb deepLearningToolkit", but I got the same error..
I'm not expert, but looks like when create the toolkit env uses installs python 3.7.16 and this is not compatible with numpy1.23 (see complete log below).
any suggestion?
thanks




stefano@cryoem1:~$ conda activate scipion3
(scipion3) stefano@cryoem1:~$ python -V
Python 3.8.16
(scipion3) stefano@cryoem1:~$ scipion3 installb deepLearningToolkit
Scipion v3.0.12 - Eugenius
Building deepLearningToolkit-0.2 ...
  Skipping command: wget -nv -c -O /home/stefano/programs/scipion/software/em/deepLearningToolkit.tgz.part http://scipion.cnb.csic.es/downloads/scipion/software/external/deepLearningToolkit.tgz
mv -v /home/stefano/programs/scipion/software/em/deepLearningToolkit.tgz.part /home/stefano/programs/scipion/software/em/deepLearningToolkit.tgz
  All targets exist.
  Skipping command: tar -xf deepLearningToolkit.tgz
  All targets exist.
  Skipping command: if ls /home/stefano/programs/scipion/software/em/xmipp/lib/libXmipp.so > /dev/null ; then touch xmippLibToken; echo ' > CUDA support find. Driver version: 525' ; else echo ; echo ' > Xmipp installation not found, please install it first (xmippSrc or xmippBin*).';echo; fi
  All targets exist.
cd /home/stefano/programs/scipion/software/em/deepLearningToolkit
export PYTHONPATH="" && eval "$(/home/stefano/programs/miniconda/bin/conda shell.bash hook)" && conda create --force --yes -n xmipp_DLTK_v0.3 python=3 pandas=0.23 scikit-image=0.14 opencv=3.4 tensorflow-gpu=1.15 keras=2.2 scikit-learn=0.22  -c anaconda && conda activate xmipp_DLTK_v0.3 && pip install numpy==1.23.0 numpy==1.23.0 && conda env export > xmipp_DLTK_v0.3.yml
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/stefano/programs/miniconda/envs/xmipp_DLTK_v0.3

  added / updated specs:
    - keras=2.2
    - opencv=3.4
    - pandas=0.23
    - python=3
    - scikit-image=0.14
    - scikit-learn=0.22
    - tensorflow-gpu=1.15


The following NEW packages will be INSTALLED:

  _libgcc_mutex      anaconda/linux-64::_libgcc_mutex-0.1-main 
  _openmp_mutex      anaconda/linux-64::_openmp_mutex-5.1-1_gnu 
  _tflow_select      anaconda/linux-64::_tflow_select-2.1.0-gpu 
  absl-py            anaconda/noarch::absl-py-0.15.0-pyhd3eb1b0_0 
  astor              anaconda/linux-64::astor-0.8.1-py37h06a4308_0 
  blas               anaconda/linux-64::blas-1.0-mkl 
  brotli             anaconda/linux-64::brotli-1.0.9-h5eee18b_7 
  brotli-bin         anaconda/linux-64::brotli-bin-1.0.9-h5eee18b_7 
  bzip2              anaconda/linux-64::bzip2-1.0.8-h7b6447c_0 
  c-ares             anaconda/linux-64::c-ares-1.18.1-h7f8727e_0 
  ca-certificates    anaconda/linux-64::ca-certificates-2023.01.10-h06a4308_0 
  cairo              anaconda/linux-64::cairo-1.14.12-h8948797_3 
  certifi            anaconda/linux-64::certifi-2022.12.7-py37h06a4308_0 
  cloudpickle        anaconda/noarch::cloudpickle-2.0.0-pyhd3eb1b0_0 
  cudatoolkit        anaconda/linux-64::cudatoolkit-10.0.130-0 
  cudnn              anaconda/linux-64::cudnn-7.6.5-cuda10.0_0 
  cupti              anaconda/linux-64::cupti-10.0.130-0 
  cycler             anaconda/noarch::cycler-0.11.0-pyhd3eb1b0_0 
  cytoolz            anaconda/linux-64::cytoolz-0.12.0-py37h5eee18b_0 
  dask-core          anaconda/noarch::dask-core-2021.10.0-pyhd3eb1b0_0 
  dbus               anaconda/linux-64::dbus-1.13.18-hb2f20db_0 
  expat              anaconda/linux-64::expat-2.4.9-h6a678d5_0 
  ffmpeg             anaconda/linux-64::ffmpeg-4.0-hcdf2ecd_0 
  flit-core          anaconda/noarch::flit-core-3.6.0-pyhd3eb1b0_0 
  fontconfig         anaconda/linux-64::fontconfig-2.14.1-h52c9d5c_1 
  fonttools          anaconda/noarch::fonttools-4.25.0-pyhd3eb1b0_0 
  freeglut           anaconda/linux-64::freeglut-3.0.0-hf484d3e_5 
  freetype           anaconda/linux-64::freetype-2.12.1-h4a9f257_0 
  fsspec             anaconda/linux-64::fsspec-2022.11.0-py37h06a4308_0 
  gast               anaconda/linux-64::gast-0.2.2-py37_0 
  giflib             anaconda/linux-64::giflib-5.2.1-h5eee18b_1 
  glib               anaconda/linux-64::glib-2.56.2-hd408876_0 
  google-pasta       anaconda/noarch::google-pasta-0.2.0-pyhd3eb1b0_0 
  graphite2          anaconda/linux-64::graphite2-1.3.14-h295c915_1 
  grpcio             anaconda/linux-64::grpcio-1.42.0-py37hce63b2e_0 
  gst-plugins-base   anaconda/linux-64::gst-plugins-base-1.14.0-hbbd80ab_1 
  gstreamer          anaconda/linux-64::gstreamer-1.14.0-hb453b48_1 
  h5py               anaconda/linux-64::h5py-2.8.0-py37h989c5e5_3 
  harfbuzz           anaconda/linux-64::harfbuzz-1.8.8-hffaf4a1_0 
  hdf5               anaconda/linux-64::hdf5-1.10.2-hba1933b_1 
  icu                anaconda/linux-64::icu-58.2-he6710b0_3 
  imageio            anaconda/linux-64::imageio-2.19.3-py37h06a4308_0 
  importlib-metadata anaconda/linux-64::importlib-metadata-4.11.3-py37h06a4308_0 
  intel-openmp       anaconda/linux-64::intel-openmp-2022.1.0-h9e868ea_3769 
  jasper             anaconda/linux-64::jasper-2.0.14-hd8c5072_2 
  joblib             anaconda/linux-64::joblib-1.1.1-py37h06a4308_0 
  jpeg               anaconda/linux-64::jpeg-9e-h7f8727e_0 
  keras              anaconda/linux-64::keras-2.2.4-0 
  keras-applications anaconda/noarch::keras-applications-1.0.8-py_1 
  keras-base         anaconda/linux-64::keras-base-2.2.4-py37_0 
  keras-preprocessi~ anaconda/noarch::keras-preprocessing-1.1.2-pyhd3eb1b0_0 
  kiwisolver         anaconda/linux-64::kiwisolver-1.4.4-py37h6a678d5_0 
  lcms2              anaconda/linux-64::lcms2-2.12-h3be6417_0 
  ld_impl_linux-64   anaconda/linux-64::ld_impl_linux-64-2.38-h1181459_1 
  lerc               anaconda/linux-64::lerc-3.0-h295c915_0 
  libbrotlicommon    anaconda/linux-64::libbrotlicommon-1.0.9-h5eee18b_7 
  libbrotlidec       anaconda/linux-64::libbrotlidec-1.0.9-h5eee18b_7 
  libbrotlienc       anaconda/linux-64::libbrotlienc-1.0.9-h5eee18b_7 
  libdeflate         anaconda/linux-64::libdeflate-1.8-h7f8727e_5 
  libffi             anaconda/linux-64::libffi-3.4.2-h6a678d5_6 
  libgcc-ng          anaconda/linux-64::libgcc-ng-11.2.0-h1234567_1 
  libgfortran-ng     anaconda/linux-64::libgfortran-ng-7.5.0-ha8ba4b0_17 
  libgfortran4       anaconda/linux-64::libgfortran4-7.5.0-ha8ba4b0_17 
  libglu             anaconda/linux-64::libglu-9.0.0-hf484d3e_1 
  libgomp            anaconda/linux-64::libgomp-11.2.0-h1234567_1 
  libopencv          anaconda/linux-64::libopencv-3.4.2-hb342d67_1 
  libopus            anaconda/linux-64::libopus-1.3.1-h7b6447c_0 
  libpng             anaconda/linux-64::libpng-1.6.37-hbc83047_0 
  libprotobuf        anaconda/linux-64::libprotobuf-3.20.3-he621ea3_0 
  libstdcxx-ng       anaconda/linux-64::libstdcxx-ng-11.2.0-h1234567_1 
  libtiff            anaconda/linux-64::libtiff-4.5.0-h6a678d5_1 
  libuuid            anaconda/linux-64::libuuid-1.41.5-h5eee18b_0 
  libvpx             anaconda/linux-64::libvpx-1.7.0-h439df22_0 
  libwebp            anaconda/linux-64::libwebp-1.2.4-h11a3e52_0 
  libwebp-base       anaconda/linux-64::libwebp-base-1.2.4-h5eee18b_0 
  libxcb             anaconda/linux-64::libxcb-1.15-h7f8727e_0 
  libxml2            anaconda/linux-64::libxml2-2.9.14-h74e7548_0 
  locket             anaconda/linux-64::locket-1.0.0-py37h06a4308_0 
  lz4-c              anaconda/linux-64::lz4-c-1.9.4-h6a678d5_0 
  markdown           anaconda/linux-64::markdown-3.4.1-py37h06a4308_0 
  matplotlib         anaconda/linux-64::matplotlib-3.5.3-py37h06a4308_0 
  matplotlib-base    anaconda/linux-64::matplotlib-base-3.5.3-py37hf590b9c_0 
  mkl                anaconda/linux-64::mkl-2019.4-243 
  mkl-service        anaconda/linux-64::mkl-service-2.3.0-py37he8ac12f_0 
  mkl_fft            anaconda/linux-64::mkl_fft-1.3.0-py37h54f3939_0 
  mkl_random         anaconda/linux-64::mkl_random-1.1.0-py37hd6b4f25_0 
  munkres            anaconda/noarch::munkres-1.1.4-py_0 
  ncurses            anaconda/linux-64::ncurses-6.4-h6a678d5_0 
  networkx           anaconda/noarch::networkx-2.6.3-pyhd3eb1b0_0 
  numpy              anaconda/linux-64::numpy-1.19.2-py37h54aff64_0 
  numpy-base         anaconda/linux-64::numpy-base-1.19.2-py37hfa32c7d_0 
  opencv             anaconda/linux-64::opencv-3.4.2-py37h6fd60c2_1 
  openssl            anaconda/linux-64::openssl-1.1.1s-h7f8727e_0 
  opt_einsum         anaconda/noarch::opt_einsum-3.3.0-pyhd3eb1b0_1 
  packaging          anaconda/linux-64::packaging-22.0-py37h06a4308_0 
  pandas             anaconda/linux-64::pandas-0.23.4-py37h04863e7_0 
  partd              anaconda/noarch::partd-1.2.0-pyhd3eb1b0_1 
  pcre               anaconda/linux-64::pcre-8.45-h295c915_0 
  pillow             anaconda/linux-64::pillow-9.3.0-py37h6a678d5_2 
  pip                anaconda/linux-64::pip-22.3.1-py37h06a4308_0 
  pixman             anaconda/linux-64::pixman-0.40.0-h7f8727e_1 
  ply                anaconda/linux-64::ply-3.11-py37_0 
  protobuf           anaconda/linux-64::protobuf-3.20.3-py37h6a678d5_0 
  py-opencv          anaconda/linux-64::py-opencv-3.4.2-py37hb342d67_1 
  pyparsing          anaconda/linux-64::pyparsing-3.0.9-py37h06a4308_0 
  pyqt               anaconda/linux-64::pyqt-5.9.2-py37h22d08a2_1 
  python             anaconda/linux-64::python-3.7.16-h7a1cb2a_0 
  python-dateutil    anaconda/noarch::python-dateutil-2.8.2-pyhd3eb1b0_0 
  pytz               anaconda/linux-64::pytz-2022.7-py37h06a4308_0 
  pywavelets         anaconda/linux-64::pywavelets-1.3.0-py37h7f8727e_0 
  pyyaml             anaconda/linux-64::pyyaml-6.0-py37h5eee18b_1 
  qt                 anaconda/linux-64::qt-5.9.7-h5867ecd_1 
  readline           anaconda/linux-64::readline-8.2-h5eee18b_0 
  scikit-image       anaconda/linux-64::scikit-image-0.14.2-py37he6710b0_0 
  scikit-learn       anaconda/linux-64::scikit-learn-0.22.1-py37hd81dba3_0 
  scipy              anaconda/linux-64::scipy-1.6.2-py37h91f5cce_0 
  setuptools         anaconda/linux-64::setuptools-65.6.3-py37h06a4308_0 
  sip                anaconda/linux-64::sip-6.6.2-py37h6a678d5_0 
  six                anaconda/noarch::six-1.16.0-pyhd3eb1b0_1 
  sqlite             anaconda/linux-64::sqlite-3.40.1-h5082296_0 
  tensorboard        anaconda/noarch::tensorboard-1.15.0-pyhb230dea_0 
  tensorflow         anaconda/linux-64::tensorflow-1.15.0-gpu_py37h0f0df58_0 
  tensorflow-base    anaconda/linux-64::tensorflow-base-1.15.0-gpu_py37h9dcbed7_0 
  tensorflow-estima~ anaconda/noarch::tensorflow-estimator-1.15.1-pyh2649769_0 
  tensorflow-gpu     anaconda/linux-64::tensorflow-gpu-1.15.0-h0d30ee6_0 
  termcolor          anaconda/linux-64::termcolor-1.1.0-py37h06a4308_1 
  tk                 anaconda/linux-64::tk-8.6.12-h1ccaba5_0 
  toml               anaconda/noarch::toml-0.10.2-pyhd3eb1b0_0 
  toolz              anaconda/linux-64::toolz-0.12.0-py37h06a4308_0 
  tornado            anaconda/linux-64::tornado-6.2-py37h5eee18b_0 
  typing_extensions  anaconda/linux-64::typing_extensions-4.4.0-py37h06a4308_0 
  webencodings       anaconda/linux-64::webencodings-0.5.1-py37_1 
  werkzeug           anaconda/noarch::werkzeug-0.16.1-py_0 
  wheel              anaconda/noarch::wheel-0.37.1-pyhd3eb1b0_0 
  wrapt              anaconda/linux-64::wrapt-1.14.1-py37h5eee18b_0 
  xz                 anaconda/linux-64::xz-5.2.10-h5eee18b_1 
  yaml               anaconda/linux-64::yaml-0.2.5-h7b6447c_0 
  zipp               anaconda/linux-64::zipp-3.11.0-py37h06a4308_0 
  zlib               anaconda/linux-64::zlib-1.2.13-h5eee18b_0 
  zstd               anaconda/linux-64::zstd-1.5.2-ha4553b6_0 



Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate xmipp_DLTK_v0.3
#
# To deactivate an active environment, use
#
#     $ conda deactivate

ERROR: Ignored the following versions that require a different python version: 1.22.0 Requires-Python >=3.8; 1.22.1 Requires-Python >=3.8; 1.22.2 Requires-Python >=3.8; 1.22.3 Requires-Python >=3.8; 1.22.4 Requires-Python >=3.8; 1.23.0 Requires-Python >=3.8; 1.23.0rc1 Requires-Python >=3.8; 1.23.0rc2 Requires-Python >=3.8; 1.23.0rc3 Requires-Python >=3.8; 1.23.1 Requires-Python >=3.8; 1.23.2 Requires-Python >=3.8; 1.23.3 Requires-Python >=3.8; 1.23.4 Requires-Python >=3.8; 1.23.5 Requires-Python >=3.8; 1.24.0 Requires-Python >=3.8; 1.24.0rc1 Requires-Python >=3.8; 1.24.0rc2 Requires-Python >=3.8; 1.24.1 Requires-Python >=3.8; 1.24.2 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement numpy==1.23.0 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6)
ERROR: No matching distribution found for numpy==1.23.0
target '/home/stefano/programs/scipion/software/em/deepLearningToolkit/xmipp_DLTK_v0.3.yml' not built (after running 'export PYTHONPATH="" && eval "$(/home/stefano/programs/miniconda/bin/conda shell.bash hook)" && conda create --force --yes -n xmipp_DLTK_v0.3 python=3 pandas=0.23 scikit-image=0.14 opencv=3.4 tensorflow-gpu=1.15 keras=2.2 scikit-learn=0.22  -c anaconda && conda activate xmipp_DLTK_v0.3 && pip install numpy==1.23.0 numpy==1.23.0 && conda env export > xmipp_DLTK_v0.3.yml')
(scipion3) stefano@cryoem1:~$

**Comment by stefanocapaldi** [comment]
> Hello [stefanocapaldi](https://github.com/stefanocapaldi), When installing DLTK be care about the enviroment you have activated, this is the one the instaler take into acount to install everything. We are working improving (and fixing issues) related to the DLTK, but so far please activate the Scipion enviroment (or anyone with a python >=3.8). Please dont hesitate contact us again. Thanks

Hi @albertmena 
I'm still struggling in installing DLTK. I have just updated scipion to the latest version and tryed again, but still got the same error, seems that the conda environment that is created for DLTK does not have the right python version for numpy 1.23.0.
any advice?
thanks
stefano

**Comment by albertmena** [comment]
Hi @stefanocapaldi, 
[Recently](https://github.com/I2PC/scipion-em-xmipp/pull/649) we have updated how Xmipp install DLTK; how to proceed:

1. Update devel branch of Xmipp` ./xmipp git pull`
2. Install Xmipp: `scipion3 run ./xmipp`
3. Link to Scipion: `scipion3 installp -p _pathTo/scipion-em-xmipp_ --devel`
4. Install DLTK `scipion3 installb deepLearningToolKit`

**Comment by stefanocapaldi** [comment]
> Hi @stefanocapaldi, [Recently](https://github.com/I2PC/scipion-em-xmipp/pull/649) we have updated how Xmipp install DLTK; how to proceed:
> 
> 1. Update devel branch of Xmipp `./xmipp git pull`
> 2. Install Xmipp: `scipion3 run ./xmipp`
> 3. Link to Scipion: `scipion3 installp -p _pathTo/scipion-em-xmipp_ --devel`
> 4. Install DLTK `scipion3 installb deepLearningToolkit`

Thanks. Just, from where should I run the first command? (`./xmipp git pull`). looks like it should point to a xmipp bin file..

**Comment by MartinSalinas98** [comment]
@stefanocapaldi from the directory where your xmipp repository is.
For example, if your installation is in `~/Documents/xmipp`, you sould add a:
```bash
cd ~/Documents/xmipp
```
at the top of the list of commans @albertmena provided.

**Comment by stefanocapaldi** [comment]
> @stefanocapaldi from the directory where your xmipp repository is. For example, if your installation is in `~/Documents/xmipp`, you sould add a:
> 
> ```shell
> cd ~/Documents/xmipp
> ```
> 
> at the top of the list of commans @albertmena provided.

@MartinSalinas98 
thanks. the thing is that i had no xmipp installation, i just installed Scipion and then the Xmipp scipion-em-xmipp plugin as described in 
https://scipion-em.github.io/docs/release-3.0.0/docs/scipion-modes/how-to-install.html
 (without installing xmipp standalone, Scipion still worked without any problems). Now I installed Xmipp standalone as described in 
https://github.com/I2PC/xmipp#xmipp
and followed @albertmena's instructions, it seems that the DLTK plugin was installed correctly. I have not yet done any work with Deeplearning but the binary is installed. Thanks

Just a curiosity about my previous configuration: is it safe to run xmipp jobs in Scipion having only scipion-em-xmipp installed and not the standalone?

**Comment by MartinSalinas98** [comment]
No, it's not, because scipion-em-xmipp is a wrapper for xmipp, which means that it runs xmipp under the hood. If xmipp is not installed, executions will fail in scipion-em-xmipp.

**Comment by stefanocapaldi** [comment]
> No, it's not, because scipion-em-xmipp is a wrapper for xmipp, which means that it runs xmipp under the hood. If xmipp is not installed, executions will fail in scipion-em-xmipp.

Ok thanks. I followed the instruction on Scipioni installation Page but i didn't realized that xmipp was essential tò install the plugin. Now It's clear
