### ISSUE TITLE
Error in import coordinates from relion

### ISSUE THREAD

**Issue by fede-pe** [scipion-em/scipion-em#520]
I am getting the following error in import coordinates protocol, when importing from a .star. This is the error:

00010:   TypeError: importCoordinates() missing 2 required positional arguments: 'fileName' and 'addCoordinate'
00011:   Protocol failed: importCoordinates() missing 2 required positional arguments: 'fileName' and 'addCoordinate'

First line of my file looks like this (picked with Gautomatch):

data_

loop_
_rlnCoordinateX #1
_rlnCoordinateY #2
_rlnAnglePsi #3
_rlnClassNumber #4
_rlnAutopickFigureOfMerit #5
431     182     255.000000	7       0.649082
842     144     195.000000	13      0.507829
1278    153     355.000000	15      0.456542
2143    158     190.000000	10      0.437050
2333    145     215.000000	5       0.503797
2769    186     90.000000	14      0.448249
3103    193     270.000000	8       0.380222

Test are passing (except for dogpicket but I have not installed appion). 

Also file names match between micrograph and coordinates (file.mrc and file.star)

**Comment by azazellochg** [comment]
Hello @fede-pe , why you are using import particles protocol while your file is clearly a coordinate file?

**Comment by JorMaister** [comment]
Re-asigned to @fonsecareyna82

**Comment by fede-pe** [comment]
Hi, obviously as @azazellochg I mean import coordinates not particles.

**Comment by azazellochg** [comment]
Okay. import coordinates protocol in relion format supports two modes: a single star file (which has to be a particle data star file that contains coordinates) and multiple star files (multiple coordinate files containing X/Y coords, each filename matching the mic names).  @fede-pe what scenario are you following?

**Comment by fede-pe** [comment]
Second case, my star file have the following fields:

_rlnCoordinateX #1
_rlnCoordinateY #2
_rlnAnglePsi #3
_rlnClassNumber #4
_rlnAutopickFigureOfMerit #5

An i have the micrographs in a second folder. As I said, in both cases file names match (file.mrc and file.star).  I have tried importing one single micrograph and associated .star but the error persist

**Comment by azazellochg** [comment]
Could you send me a couple of MRC and the matching star files?

**Comment by azazellochg** [comment]
Looking at your error, it seems to be executing https://github.com/scipion-em/scipion-em/blob/devel/pwem/protocols/protocol_import/coordinates.py#L142 line, which means it is not importing in relion format

**Comment by azazellochg** [comment]
PS. please also report relion plugin and pwem version or attach full logs.

**Comment by fede-pe** [comment]
Hello Grigory, I am sorry but I am not allowed to disclosure any data. How does the expected relion file looks like? maybe que header / labels are different that the ones I have?

relion and scipion core plugins are in devel mode and update:

scipion-em            3.7.0       
scipion-pyworkflow    3.6.0
scipion-app           3.4.0       
scipion-em-relion     5.0.0b8

[run.stderr.txt](https://github.com/user-attachments/files/16438528/run.stderr.txt)
[run.stdout.txt](https://github.com/user-attachments/files/16438529/run.stdout.txt)

**Comment by azazellochg** [comment]
Hi, no problem. I'll dig more into this. Thank you for the versions

**Comment by azazellochg** [comment]
I cannot reproduce your error:
![image](https://github.com/user-attachments/assets/c9ca9fc4-f405-45e8-a3ea-94f2ad5465d6)
Can you run the test: scipion3 tests relion.tests.test_protocols_2d.TestRelionImportCoords

**Comment by fede-pe** [comment]
Test are passing correctly.

Nonetheless I worked wrround this problem. I have reextracted the coordinates (outside scipion) and import the new particles.star file that points to the extracted particles. I know this is not equivalent to importing the coordinates, but it solved my problem.

**Comment by azazellochg** [comment]
Ok. Are you able to import coordinates using this single "particles.star" file?

**Comment by azazellochg** [comment]
Could you send me micrographs.sqlite that you are using? And maybe a couple of star files? I don't need mrc images

**Comment by fede-pe** [comment]
Yes, that also works. I guess that the output .star files from that gautomatch version are compatible with our import (?).

Nonetheless I would consider the problem as solved.

**Comment by azazellochg** [comment]
I've just noticed you are using pwem 3.7.0. There have been changes in import coordinates since then: https://github.com/scipion-em/scipion-em/compare/v3.7.0...devel Are you able to update and test?

**Comment by azazellochg** [comment]
> > Yes, that also works. I guess that the output .star files from that gautomatch version are compatible with our import (?).
> > Nonetheless I would consider the problem as solved.
> 
> Good point, I'll test gautomatch output which I haven't done yet.

![image](https://github.com/user-attachments/assets/9fc454e6-492e-45ac-a4c2-3005060685db)
importing *automatch.star worked for me. So it could be that you need to update pwem

**Comment by fede-pe** [comment]
Great thanks grigory!

**Comment by azazellochg** [comment]
has it worked after update?

**Comment by fede-pe** [comment]
Yes, the error is not appearing anymore, although pwem was already updated. I think it is safe to close this issue
