### ISSUE TITLE
import coords test fails on buildbot

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em#540]
scipion3 tests pwem.tests.protocols.test_protocols_import_coords.TestImportCoordinates

```
 File "/home/buildbot/buildbot-worker/devel/scipion/scipion-em/pwem/tests/protocols/test_protocols_import_coords.py", line 199, in testImportCoordinates
 os.link(os.path.join(micsDir, micsList[0]), newMic0)
OSError: [Errno 18] Invalid cross-device link: '/home/buildbot/buildbot-worker/devel/scipion/data/tests/xmipp_tutorial/micrographs/BPV_1386.mrc' -> '/tmp/tmpy6kvdhg9/micrograph_BPV_1.mrc'
```

**Comment by pconesa** [comment]
Thanks! I dont understand why now is failing. 

There error is cause by the test creating links in a different HD unit.

AS far as I know,  this test is not new nor we have change the testing machine HDs?

**Comment by pconesa** [comment]
It may be failing for months though

**Comment by pconesa** [comment]
Ok, adding a prefix to be a path in the same filesystem fixes this. Will be in the next release
