### ISSUE TITLE
Unsolved reference in viewer_chimera.py --> ChimeraProjectionClient

### ISSUE THREAD

**Issue by JorMaister** [scipion-em/scipion-em#57]
I've found no definition to ChimeraProjectionClient anywhere.

class ChimeraClientView(pwviewer.CommandView):
    """ View for calling an external command. """

    def __init__(self, inputFile, **kwargs):
        self._inputFile = inputFile
        self._kwargs = kwargs

    def show(self):
        if self._kwargs.get('showProjection', False):
            ChimeraProjectionClient(self._inputFile, **self._kwargs)
        else:
            ChimeraAngDistClient(self._inputFile, **self._kwargs)

**Comment by azazellochg** [comment]
I think this is long fixed.
