### ISSUE TITLE
ctf consensus test fails

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em#88]
scipion test pwem.tests.workflows.test_workflow_xmipp_ctf_consensus.TestCtfConsensus fails because of this very brave comparison:
https://github.com/scipion-em/scipion-em/blob/daf28211688e84d44595f6d3f107181b9025d930/pwem/tests/workflows/test_workflow_xmipp_ctf_consensus.py#L62

Different ctf estimation programs will never return exactly the same defocus vales.

**Comment by pconesa** [comment]
@azazellochg firstCTF should be the same as refCTF....both should be xmippCTF. Recently consensus had a new parameter to average the ctf values and that is why it was failing.

**Comment by dmaluenda** [comment]
Hi Both,

Yes, as Pablo said, we updated the CTFconsensus to include a new functionality on averaging the defocus of the two CTFs in the inputs. This functionality can  be turn off in the form.

We had put it as default, but I think now that it would be better to keep the same behavior as before by default (see bc803e6d411bba30d7175012845f9d0ad01b2dd2).

Also, I will include a new test to check this new functionalities (also for the addition of metadata columns present in the secondary but not in the primary)
